obj-$(CONFIG_SND_SOC_BOLERO) += bolero-cdc.o bolero-cdc-utils.o bolero-cdc-regmap.o bolero-cdc-tables.o
obj-$(CONFIG_WSA_MACRO) += wsa-macro.o
obj-$(CONFIG_VA_MACRO) += va-macro.o
obj-$(CONFIG_TX_MACRO) += tx-macro.o
obj-$(CONFIG_RX_MACRO) += rx-macro.o
