obj-$(CONFIG_SND_SOC_MSM_QDSP6V2_INTF) += msm-audio-event-notify.o audio_calibration.o audio_cal_utils.o q6adm.o \
                                            q6afe.o q6asm.o q6audio-v2.o q6voice.o q6core.o q6common.o rtac.o q6lsm.o audio_slimslave.o adsp_err.o msm_audio_ion.o avtimer.o q6_init.o

obj-$(CONFIG_XT_LOGGING) += sp_params.o
obj-$(CONFIG_AFE_HWDEP) += q6afecal-hwdep.o
obj-$(CONFIG_DTS_SRS_TM) += msm-dts-srs-tm-config.o
obj-$(CONFIG_MSM_ADSP_LOADER) += adsp-loader.o
obj-$(CONFIG_MSM_QDSP6_NOTIFIER) += audio_notifier.o audio_ssr.o
obj-$(CONFIG_MSM_QDSP6_PDR) += audio_pdr.o
obj-$(CONFIG_MSM_ULTRASOUND) += usf.o usfcdev.o q6usm.o
obj-$(CONFIG_MSM_MDF) += msm_mdf.o
obj-$(CONFIG_VOICE_MHI) += voice_mhi.o
obj-y += codecs/
